FROM python:3.11

WORKDIR /app

COPY ./text_analyzer/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./text_analyzer .
COPY ./shared /app/shared

CMD ["python", "-m", "analizer_orchestrator"]