FROM python:3.11

WORKDIR /app

COPY ./dataconsumption/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./dataconsumption .
COPY ./shared /app/shared

CMD ["python", "-m", "consumption_orchestrator"]