FROM python:3.11

WORKDIR /app

COPY ./Ingestionservice/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./Ingestionservice .
COPY ./shared /app/shared

CMD ["python", "-m", "ingestion_orchestrator"]