FROM python:3.11

WORKDIR /app

COPY ./user_interface/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./user_interface .
COPY ./shared /app/shared

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]


